### ISSUE TITLE
github commands - $30

### ISSUE THREAD

**Issue by zach-nervana** [dwiel/talon_community#17]
create commands for all of the github keyboard shortcuts on the website

**Comment by nodonnel** [comment]
I'm working on this, will be done soon.

**Comment by nodonnel** [comment]
Source: https://help.github.com/articles/using-keyboard-shortcuts/

Still need to do:
       * Contexts & shorcuts for:
            * Source code browsing
            * Comments (markdown)
            * Project boards
            * Notifications
       * Make global (firefox.py) "page mode" and "tridactyl mode" rules
       * Test rule for "Add a single comment on a pull request diff"

   Bugs:
       * On Issues/Pull Requests List Pages, "cmd-/"
         conflicts w/ Firefox shortcuts

**Comment by nodonnel** [comment]
Everything that is still on the "to do" list is only there because of challenges in defining the context, i.e. window title does not provide sufficient information.

**Comment by dwiel** [comment]
perhaps this is what you are talking about last night, but when i try this right now many of the contexts are never activated. For some reason the title of this page for example is empty, and so none of the contexts are activated. Perhaps we should just put all of these in scope for all of firefox for now?

**Comment by dwiel** [comment]
It looks like this was actually a bug in talon/firefox.
