### ISSUE TITLE
exclude config.json from repo

### ISSUE THREAD

**Issue by jcooper-korg** [dwiel/talon_community#177]
since this file is the user's personal config- it should be excluded from the repo.

(Note the repo's config.json specifies window_management.change_screen_mode=full, which differs from the default specified in window_snap.py's call to config.get.  maybe the default should be changed to full when remove config.json from the repo?

**Comment by jcooper-korg** [comment]
also these user .json  files like config/vocab*/webpages/servers/searches could be added to .gitignore?

**Comment by dwiel** [comment]
This has been done, thank you
