### ISSUE TITLE
Keeper is so useful, can I apply it everywhere?

### ISSUE THREAD

**Issue by Madd0g** [dwiel/talon_community#190]
Maybe I'm misunderstanding something, but it seems like `<dgndictation>` can be interrupted by any existing command? I mostly use `say` and `title` (and other formatters for code) and it seems like they stop if any one of the words is an existing command?

I know the docs mention this:

>The `phrase` command will only preserve literally the first part of the utterance. Anything that might be a command after the first word will be interpreted as such

I use `keeper` to overcome this, but I feel like the more commands I create that use `<dgndictation>`, the more I want the keeper behavior (almost) everywhere. Because the more commands I create, the bigger the chance they'll interrupt the `say/phrase/title` commands.

I'm imagining all kinds of way to hack this in (with `pre:phrase` in `formatters.py`), but I'm wondering how many people are having the same problem? Maybe there is a built-in solution to have `<dgndictation>` not stop?

Thanks

**Comment by dwiel** [comment]
you can check on the slack, but I think there might be a way to capture more words like you want with `<dgndictation>+` or `<dgndictation>++`. I don't remember the specifics though, I'd check with aegis on slack

**Comment by Madd0g** [comment]
I found a mention of this [here](https://whalequench.club/blog/2019/09/03/learning-to-speak-code.html). You're exactly right, `<dgndictation>++` is the solution.
