### ISSUE TITLE
`trail` often misses words

### ISSUE THREAD

**Issue by zach-nervana** [dwiel/talon_community#32]
if the line contains: `hello world hello world` end of the cursor is at the end, `trail world` highlights the first world and not the last one.

**Comment by dwiel** [comment]
it seems like oftentimes the word that actually gets highlighted is the second previous word not the first previous.

**Comment by dwiel** [comment]
there seem to be some pretty serious bugs in this implementation, not limited to the ones listed here.

**Comment by jcooper-korg** [comment]
my implementation as of 531b2831a9d90823c3d8c24cffe0b69e6db5664a doesn't appear to have this issue.

**Comment by dwiel** [comment]
It looks like I can't reproduce this bug anymore either ...
