### ISSUE TITLE
std file should be refactored 

### ISSUE THREAD

**Issue by dylan-chong** [dwiel/talon_community#39]
std.py file is rather hard to understand, and could do with some refactoring. Here are some points/ideas that I am thinking about

- There is stuff there, like git commands that is crammed into this file. Ideally files should have a single responsibility so the git stuff should be moved into a separate file.
- the formatters could be refactored to turn lines like this 
`"snake": (True, lambda i, word, _: word if i == 0 else "_" + word)` into something nicer like this with a easier to understand and use API 
`”snake": Formatter(delimiter=‘_’),`
- the FormatText function is rather hard to understand, especially for beginners, so should be refactored to be easier to understand

For more details about the format text (local) API, there could be other options like `prefix=‘“‘, suffix=‘”’]` and something to do with upper and lower casing which I haven't thought of a good solution for you

I would actually like to do some of this refactoring, so let me know if this is an idea you would like, and what things above you agree/disagree with

**Comment by dylan-chong** [comment]
Regarding the git grammar, see #40  for some more ideas, although  this refactoring can be done completely independently of that issue

**Comment by dylan-chong** [comment]
Great, i'll get started on this sometime

**Comment by dylan-chong** [comment]
Some more (incomplete list of) ideas for refactoring/tidying

---

These lines look a bit dodgy to me:

        "comma <dgndictation> [over]": [", ", spoken_text],
        "period <dgndictation> [over]": [". ", sentence_text],

They can create some unexpected results because `comma` and `period` can and probably are used for the symbols.

---

        "tarpy": [Key("tab"), Key("tab")],

not sure what the point of this is, as `tab tab` is the same number of syllables as `tarpy`, so I'm not sure how useful this actually is

---

        "triple quote": "'''",

in my Aenea grammar for vim, I had a double/triple/quadruple rule for doing this sort of thing but more generalised. That's something we could consider refactoring in the future

---

        "state import": "import ",
        "state class": "class ",
	#...
        "word queue": "queue",

the `"word <dgnwords>”` mapping further up the file makes these above things a little bit redundant

---


        "question [mark]": "?",
        "tilde": "~",
        "(bang | exclamation point)": "!",
        "dollar [sign]": "$",
        "downscore": "_",
        "colon": ":",



These things could definitely be moved into the basic keys file. I'll try to move some of these out into the basic keys file


——


Keep in mind these are just suggestions, and most of these can probably be refactored in the future. For the first stage of refactoring, I'll just stick to moving stuff out in to separate files for now

**Comment by dylan-chong** [comment]
@dwiel What you suggest about the context for stuff like Git in the terminal? Currently the terminal file is inside apps, and according to the readme there should always be a context filter for a file inside apps. If I break up the terminal file and put Git stuff in it, then I won't be able to put a context very easily.

**Comment by wizonesolutions** [comment]
lunixbochs has said that basic_keys should be for physical keypresses that
don't require holding shift on a US layout. `_` requires holding shift so I
think std is the right place

**Comment by dwiel** [comment]
Many symbols are already in text/symbol.py, perhaps we should just consolidate there.

**Comment by dwiel** [comment]
Context of git is tricky. It is typically used in the terminal, but I also occasionally use it in a browser (in browser terminals, or chat/forum/QA discussion about git process) and in slack.

**Comment by dwiel** [comment]
Perhaps it should go in lang or text instead? If I ever say git reset hard in any context I really mean `got reset --hard` for example.

**Comment by dwiel** [comment]
Same goes with most terminal apps I would say. kubectrl, docker, etc.

**Comment by dylan-chong** [comment]
Yeah I agree, I definitely found that I use git stuff and messaging apps to help out friends, and in non-standard terminals (eg Kitty, Alacritty). 

I suppose Lang would make the most sense? And I guess, don't put any sort of filters on the context, and just leave a comment saying way there is no filters?

**Comment by dwiel** [comment]
Yeah, lang sounds good to me.

**Comment by dwiel** [comment]
I just made a few more reorganizations and `std.py` is now completely removed

**Comment by dwiel** [comment]
thanks again @dylan-chong for doing so much cleanup

**Comment by dylan-chong** [comment]
awesome! no problem!
