### ISSUE TITLE
add pep8 + ci checks

### ISSUE THREAD

**Issue by dylan-chong** [dwiel/talon_community#42]
This is a minor suggestion, but it would be nice if our code followed some kind of linting standard, although it is more of a prettiness thing rather than a practical thing.

**Comment by dylan-chong** [comment]
I may be biased towards following pep8 because my editor is set up to highlight every violation with red (there is red everywhere and every single file) :P

**Comment by dwiel** [comment]
I agree. Not too long ago, the entire code base was autolinted with black.
I suggest we continue with it.

CI would be nice for sure

**Comment by g-sam** [comment]
> This is a minor suggestion

I disagree, this is a killer suggestion to be done ASAP!! Helps me catch errors.

**Comment by dwiel** [comment]
I propose black for canonical styling. What about for linting? Do you guys have a preferred style/linter CI setup? Travis-CI?

**Comment by dwiel** [comment]
I've got drop in config for pytest on travis, but style/linting, anyone else?

**Comment by g-sam** [comment]
Black 👍 
I don't mind which linter. I'm not that well versed in the Python ecosystem. I have seen pyflakes, pylint, and mccabe used in combination.
I have used Travis and Circle CI - either fine by me!
