### ISSUE TITLE
`big word prev` (do not separate words on -./ only on ` `)

### ISSUE THREAD

**Issue by dwiel** [dwiel/talon_community#48]
similar to `wordprev` but using different word separators. This would be useful for selecting something like /long/file/name, spine-case-names, etc

**Comment by zach-nervana** [comment]
https://github.com/dwiel/talon_community/blob/master/misc/generic_editor.py#L223

**Comment by isomorphisms** [comment]
https://www.youtube.com/watch?v=6bUUlGK7Lx4
