### ISSUE TITLE
VSCode script trying to import missing repeat_function

### ISSUE THREAD

**Issue by adamharms** [dwiel/talon_community#9]
repeat_function is being imported from utils but it doesn't exist in the community version of utils

@christianhultin could you please add the repeat_function that the VS Code script is calling into the the script, the utils script, or adding the feature to the repeat script? 

Thanks!

**Comment by christianhultin** [comment]
sorry my bad! I will take a look at it later today, or tomorrow

**Comment by zach-nervana** [comment]
is this fixed now?

**Comment by adamharms** [comment]
Yes, the error is no longer present, thanks @christianhultin
